### ISSUE TITLE
Elasticsearch not generating data for Kibana

### ISSUE THREAD

**Issue by hs-pedro** [acesso-io/techcore-cvat#1]
### Expected Behaviour
Kibana should display data using elasticsearch

### Current Behaviour
KIbana app works, but no data is displayed

### Possible Solution
From [FAQ question](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/faq.md#kibana-app-works-but-no-logs-are-displayed), this is a known issue that we should configure the elastic search to avoid the disk space issue:
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/disk-allocator.html

### Steps to Reproduce (for bugs)

1. Access kibana app: `/analytics/app/kibana`
2. There will be no data displayed

----
Debug:
1. SSH into VM instance
2. `sudo docker logs cvat_elasticsearch | grep -i flood stage`

**Comment by rafascm** [comment]
The solution was to set

```
PUT /cvat.client/_settings
{
  "index.blocks.read_only_allow_delete": null
}
```

and then set it to `false` after.

This happens because as stated in https://www.elastic.co/guide/en/elasticsearch/reference/6.8/disk-allocator.html

"The index block must be released manually when the disk utilization falls below the high watermark."
