### ISSUE TITLE
Include task name in sendTaskInfo events

### ISSUE THREAD

**Issue by hs-pedro** [acesso-io/techcore-cvat#13]
### Expected Behaviour
Receive the task name in `Send task info` events from elasticsearch

### Current Behaviour
There is no event that contains the task name in its payload

### Possible Solution
Following the front-end pipeline:
1. Components use `saveAnnotationAsync` to dispatch a redux action that will log the event
https://github.com/acesso-io/techcore-cvat/blob/467dbce203cc615c24aed170994280071b89c498/cvat-ui/src/containers/annotation-page/top-bar/annotation-menu.tsx#L93-L95

2. `saveAnnotationAsync` action will log with payload from `jobInfoGenerator` function that uses either a `jobInstance` or `sessionInstance` - `Job` class is derived from `Session`
https://github.com/acesso-io/techcore-cvat/blob/467dbce203cc615c24aed170994280071b89c498/cvat-ui/src/actions/annotation-actions.ts#L1108-L1110

3. On `jobInfoGenerator`, use the `job` instance to get the `task` property, which contains the `name` to be sent on the event
https://github.com/acesso-io/techcore-cvat/blob/467dbce203cc615c24aed170994280071b89c498/cvat-core/src/session.js#L724-L734

https://github.com/acesso-io/techcore-cvat/blob/467dbce203cc615c24aed170994280071b89c498/cvat-ui/src/actions/annotation-actions.ts#L85-L86

```diff
diff --git a/cvat-ui/src/actions/annotation-actions.ts b/cvat-ui/src/actions/annotation-actions.ts
index 898306a0..50fb6138 100644
--- a/cvat-ui/src/actions/annotation-actions.ts
+++ b/cvat-ui/src/actions/annotation-actions.ts
@@ -85,6 +85,7 @@ export function computeZRange(states: any[]): number[] {
 async function jobInfoGenerator(job: any): Promise<Record<string, number>> {
     const { total } = await job.annotations.statistics();
     return {
+        'taskname': job.task.name,
         'frame count': job.stopFrame - job.startFrame + 1,
         'track count':
             total.rectangle.shape +

```

**Comment by rafascm** [comment]
After adding `taskname` to `cvat-ui/src/actions/annotation-actions.ts`, it was necessary to `refresh` the `field list`:

![index_pattern_mapping](https://user-images.githubusercontent.com/19693527/115266534-abde0380-a10e-11eb-9080-8f0d93a9faad.png)

With `taskname.keyword` available, it's possible to create an aggregation using it

**Comment by rafascm** [comment]
to refresh the field list, navigate to `Management -> Index Patterns -> Refresh Button` next to `Delete Button` at the top right corner
