### ISSUE TITLE
Generate daily report from Kibana

### ISSUE THREAD

**Issue by hs-pedro** [acesso-io/techcore-cvat#3]
Be able to use kibana app to query, via elastic search, the daily activity so we can generate a CSV report. As synced with @vinicius-nogueira , a good start on the report would be to group by assignee the activity inside CVAT:
- batch label
- how many images were annotated (in total)
- from those images, how many were **live**, **spoof**, **undefined**

| user  |  batch  |  live  |  spoof  |  undefined  |  total  |
| ------------------- | ------------------- | ------------------- | ------------------- | ------------------- | ------------------- |
|  user1 |  batch1 |  200 |  50 |  2 |  252 |
|  user1 |  batch2 |  100 |  20 |  10 |  130 |
|  user2 |  batch3 |  50 |  10 |  40 |  100 |

**Comment by rafascm** [comment]
To generate a report as requested, it's necessary to follow these definitions:

### user, batch:
- Buckets
   -  Add sub-buckets
      - Split Rows
         - Terms: `userid.keyword` / `taskname.keyword`
         - Order by: Alphabetical
         
### live, spoof, undefined: 
- Metrics
   - Aggregation: Top Hit
   - Field: `tagLive` / `tagSpoof` / `tagUndefined`
   - Aggregate with: Max
   - Size: 1
   - Sort on: `@timestamp`
   - Order: Descending

### total:
- Metrics
   - Aggregation: Max
   - Field: `object count`

![Screenshot from 2021-04-22 18-53-11](https://user-images.githubusercontent.com/19693527/115792878-6f760600-a3a1-11eb-9be5-8667d85d21a5.png)
