### ISSUE TITLE
Parse multiple tags and publish to GCP

### ISSUE THREAD

**Issue by hs-pedro** [acesso-io/techcore-cvat#31]
Acho que faz sentido, sobre as multiplas tags esse seria um brainstorm das formas como pensei de resolver:
1. Salvar como array e ter um parser adicional no DataFlow. Exemplo
##### 5.txt
```
imagem1,lote1,spoof:sunglasses
```
##### DataFlow parser
```javascript
line = "imagem1,lote1,spoof:sunglasses"
[image_id, task_name, tags] = line.split(',')

/* image_id = "imagem1"
 * task_name = "lote1"
 * tags = "spoof:sunglasses"
 */

tags.split(':').forEach(tag => {
  // Insert tag as a column with boolean value
});
```

2. Salvar cada tag em um campo separado por virgula. Exemplo
##### 5.txt
```
imagem1,lote1,spoof,sunglasses
```
##### DataFlow parser
```javascript
line = "imagem1,lote1,spoof,sunglasses"
[image_id, task_name, ...tags] = line.split(',')

/* image_id = "imagem1"
 * task_name = "lote1"
 * tags = ["spoof", "sunglasses"]
 */

tags.forEach(tag => {
  // Insert tag as a column with boolean value
});
```

3. Definir algumas tags que a gente quer parsear e descartar o resto, i.e: `live`, `spoof` e `undefined`
4. Salvar na tabela do BigQuery dentro da coluna `tag` um array de strings 

Você já pensou em alguma outra forma @jmichaelsilva ? O que acha dessas? Eu pessoalmente iria pra segunda, fica mais simples do que ter outro caractere/parser só pras tags, porém fica menos escalável pra ter outros campos (teriam que entrar antes de começar as tags pra não quebrar o parser)

_Originally posted by @hs-pedro in https://github.com/acesso-io/techcore-cvat/pull/30#discussion_r677450609_

**Comment by jmichaelsilva** [comment]
Eu seguiria o exemplo 1 -> `imagem1,lote1,spoof:sunglasses` e guardaria o conteúdo completo dentro da coluna tag `spoof:sunglasses` sem tratar o dado, passando a responsa do tratamento para a consulta (é uma proposta inicial).

**Comment by hs-pedro** [comment]
Solved by #30
