### ISSUE TITLE
Generate report activity by batch

### ISSUE THREAD

**Issue by hs-pedro** [acesso-io/techcore-cvat#4]
Be able to use kibana app to query, via elastic search, the activity by batch so we can generate a CSV report. As synced with @vinicius-nogueira , a good start to this report would be to get details of batch and user:
- batch label
- assignee (user)
- how many images were annotated (in total)
- from those images, how many were **live**, **spoof**, **undefined**
- status (`Completed`, `Validation`, `Pending`) - we can exclude `completed`, since theoratically a completed batch was already validated by @vinicius-nogueira 

| batch  |  user  |  live  |  spoof  |  undefined  |  total  | status |
| ------------------- | ------------------- | ------------------- | ------------------- | ------------------- | ------------------- |  ------------------- |
| batch1 |  user1 |  200 |  50 |  2 |  252 | Validation |
|  batch2 | user1 | 100 |  20 |  10 |  130 | Validation |
|  batch3 | user2 |  50 |  10 |  40 |  100 | Pending |

**Comment by rafascm** [comment]
To generate a status report, it's necessary to follow these definitions:

status:
- Buckets
   - Add sub-buckets
      - Split Rows
         - Terms: `status.keyword`
         - Order by: Custom Metric
            - Aggregation: Max
            - Field: `@timestamp`
            - Order: Descending
            - Size: 1

![Screenshot from 2021-04-23 16-42-04](https://user-images.githubusercontent.com/19693527/115925363-621b5300-a457-11eb-9f0d-ec4bb0b2fc48.png)

**Comment by rafascm** [comment]
Generating status report v1:

### `status`, `user`
Metrics
- Aggregation: Top Hit
- Field: `status.keyword` / `userid.keyword`
- Aggregate with: Concatenate
- Size: 1
- Sort on: `@timestamp`
- Order: Descending `for status` / Ascending `for user`

### `live`, `spoof`, `undefined`
Metrics
- Aggregation: Top Hit
- Field: `tagLive` / `tagSpoof` / `tagUndefined`
- Aggregate with: Max
- Size: 1
- Sort on: `@timestamp`
- Order: Descending

### `total`
Metrics
- Aggregation: Max
- Field: `object count`

### `first @timestamp`
Metrics
- Aggregation: Top Hit
- Field: `@timestamp`
- Aggregate with: Concatenate
- Size: 1
- Sort on: `@timestamp`
- Order: Ascending

### `last @timestamp`
Metrics
- Aggregation: Max Bucket
- Bucket
   - Sub Aggregation: Terms
   - Field: `event.keyword`
   - Advanced
      - Include: `Send task info`
- Metric
   - Max: `@timestamp`

### `batch`
Buckets
- Add sub-buckets
- Split Rows
- Terms: `taskname.keyword`
- Order by: Alphabetical
- Size: 1000

### `job`
Buckets
- Add sub-buckets
- Split Rows
- Terms: `job_id`

![Screenshot from 2021-04-28 18-44-06](https://user-images.githubusercontent.com/19693527/116476554-c2dcce00-a851-11eb-875a-2bf87d09c20e.png)
