### ISSUE TITLE
Enumeração de usuários (Páginas)

### ISSUE THREAD

**Issue by vinicius-nogueira** [acesso-io/techcore-cvat#58]
### Avaliação de Segurança - CVAT (07/2021)

![Screenshot from 2021-11-16 18-19-45](https://user-images.githubusercontent.com/58186122/142138369-893081a8-fa35-45b6-988c-3a9e83f5c20e.png)

**Vulnerabilidade média: Não compromete diretamente o sistema ou os dados, pode ser utilizado para obter acesso adicional.**

---

**Descrição:** 
Foi verificado a possibilidade de enumerar usuários contidos na aplicação.

**Risco:** 
Um atacante poderia utilizar essa informação para realizar ataques direcionados à aplicação.

**Recomendação:** 
Não incluir informações sensíveis nas respostas contidas na plataforma.

**Evidência:**

![Screenshot from 2021-11-17 02-08-59](https://user-images.githubusercontent.com/58186122/142138656-8cdd14c1-dc0b-4723-8082-b99f686eb90f.png)

![Screenshot from 2021-11-17 02-08-48](https://user-images.githubusercontent.com/58186122/142138668-c03370ec-daba-4445-8166-cc8ccb87a23b.png)

---

**Mais informações:**

[OWASP A5:2017](https://owasp.org/www-project-top-ten/2017/A5_2017-Broken_Access_Control)
[Planilha de Vulnerabilidades](https://docs.google.com/spreadsheets/d/1s3cNtNeEcf52Zu4vp0NVM3EgvsG-Y3ygCcqsr0dSqHY/edit?usp=sharing)
[Apresentação do Pentest](https://docs.google.com/presentation/d/1VQd_XGc0dKwmVUbDadYoqL3VWITJYJSz_A-yWGPPjts/edit?usp=sharing)
[Links Úteis](https://unico-idtech.slack.com/archives/C02HK5EU3BJ/p1636721402072600)

**Comment by GabrielRocha** [comment]
Issue resolvida no PR - https://github.com/acesso-io/techcore-cvat/pull/87
