### ISSUE TITLE
Token Anti-CSRF sem validação

### ISSUE THREAD

**Issue by vinicius-nogueira** [acesso-io/techcore-cvat#61]
### Avaliação de Segurança - CVAT (07/2021)

![Screenshot from 2021-11-17 08-32-39](https://user-images.githubusercontent.com/58186122/142193212-43e4169f-e811-4151-8122-9897983146ec.png)

**Vulnerabilidade média: Não compromete diretamente o sistema ou os dados, pode ser utilizado para obter acesso adicional.**

---

**Descrição:** 
Foi verificado a possibilidade de execução de requisições removendo o token anti CSRF.

**Risco:** 
Um atacante poderia utilizar essa informação para realizar ataques direcionados à aplicação, como ataques de Cross Site Request Forgery.

**Recomendação:**
Implementar a validação do token em cada requisição.

**Evidência:**

![Screenshot from 2021-11-17 08-36-23](https://user-images.githubusercontent.com/58186122/142193814-0ae7bb8c-7518-4b51-9efd-ee51a5fd1e16.png)

![Screenshot from 2021-11-17 08-36-40](https://user-images.githubusercontent.com/58186122/142194142-62bddf9c-cbc3-441d-9a1c-b9e67bdf98d1.png)

---

**Mais informações:**

[OWASP A2:2017](https://owasp.org/www-project-top-ten/2017/A2_2017-Broken_Authentication)
[Planilha de Vulnerabilidades](https://docs.google.com/spreadsheets/d/1s3cNtNeEcf52Zu4vp0NVM3EgvsG-Y3ygCcqsr0dSqHY/edit?usp=sharing)
[Apresentação do Pentest](https://docs.google.com/presentation/d/1VQd_XGc0dKwmVUbDadYoqL3VWITJYJSz_A-yWGPPjts/edit?usp=sharing)
[Links Úteis](https://unico-idtech.slack.com/archives/C02HK5EU3BJ/p1636721402072600)

**Comment by hs-pedro** [comment]
Foi alinhado com o time de segurança para matermos da forma como está. Hoje temos dois fluxos de autenticação no CVAT:
1. token-based (stateless) usando o Authorization com o valor passado no retorno do /auth/login
2. session-based (stateful) usando o cookie de sessão + CSRF Token

Usando o `Authorization`, não estamos validando CSRF, porque não estamos fazendo login por sessão. Este é o caso do teste.
